name: Deploy VitePress

on:
  push:
    branches:
      - main # Deploy automatically on push to main branch
  workflow_dispatch: # Allows manual deployment from GitHub UI

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Setup Node.js and enable Corepack
        uses: actions/setup-node@v4
        with:
          node-version: '23.11.0' # Using specific Node.js version
          cache: 'pnpm' # Enable dependency caching

      - name: Enable pnpm using Corepack
        run: corepack enable && corepack prepare pnpm@latest --activate

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Verify pnpm installation
        run: pnpm --version

      - name: Debug PATH
        run: echo $PATH && which pnpm

      - name: Build VitePress
        run: pnpm run docs:build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
          publish_dir: .vitepress/dist
          publish_branch: gh-pages
          dotfiles: true
